# Run unit tests on push.
# Loosely based on https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-multiple-python-versions

name: Python build

on: [push]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15-intel # Use Intel macOS to support older Python versions.
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip install .
      - name: Test
        run: python -m unittest discover -s .
